import React from "react";
import "./ClinicalDashboard.css";

export default function ClinicalDashboard() {

  return (
      <div className="clinical-dashboard">

            <div className="dashboard-header">
                    <h1>Doctor Dashboard</h1>
                            <p>Clinical Command Interface</p>
                                  </div>

                                        <div className="dashboard-grid">

                                                {/* LEFT SIDE */}
                                                        <div className="dashboard-left">

                                                                  <div className="panel">
                                                                              <h3>Patient Queue</h3>
                                                                                          <p>No pending cases</p>
                                                                                                    </div>

                                                                                                              <div className="panel">
                                                                                                                          <h3>AI Alerts</h3>
                                                                                                                                      <p>No alerts</p>
                                                                                                                                                </div>

                                                                                                                                                        </div>

                                                                                                                                                                {/* RIGHT SIDE */}
                                                                                                                                                                        <div className="dashboard-right">

                                                                                                                                                                                  <div className="consultation-card">

                                                                                                                                                                                              <h2>Incoming Telemedicine Consultation</h2>

                                                                                                                                                                                                          <p className="consult-id">
                                                                                                                                                                                                                        Consultation ID: CONS-1773052494441
                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                <div className="consult-section">
                                                                                                                                                                                                                                                              <h4>Subjective</h4>
                                                                                                                                                                                                                                                                            <p>Patient reports severe abdominal pain.</p>
                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                    <div className="consult-section">
                                                                                                                                                                                                                                                                                                                  <h4>Objective</h4>
                                                                                                                                                                                                                                                                                                                                <p>Temperature 38.9°C, pulse elevated.</p>
                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                        <div className="consult-section">
                                                                                                                                                                                                                                                                                                                                                                      <h4>Assessment</h4>
                                                                                                                                                                                                                                                                                                                                                                                    <p>Possible bacterial infection.</p>
                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                            <div className="consult-section">
                                                                                                                                                                                                                                                                                                                                                                                                                          <h4>Next Steps</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>Doctor consultation recommended.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="consult-actions">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button className="accept-btn">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Accept Consultation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button className="decline-btn">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Decline
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }