import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";

const DoctorConsultationRequests = () => {

  const [requests, setRequests] = useState([]);
    const navigate = useNavigate();

      useEffect(() => {

          const fetchRequests = async () => {

                try {

                        const response = await fetch("/consultation/pending");

                                const data = await response.json();

                                        if (response.ok) {
                                                  setRequests(data);
                                                          }

                                                                } catch (err) {
                                                                        console.error("Failed to fetch consultation requests", err);
                                                                              }

                                                                                  };

                                                                                      fetchRequests();

                                                                                        }, []);

                                                                                          const acceptConsultation = (consultationId) => {

                                                                                              navigate(`/consultation/${consultationId}`);

                                                                                                };

                                                                                                  const declineConsultation = async (consultationId) => {

                                                                                                      try {

                                                                                                            await fetch(`/consultation/decline/${consultationId}`, {
                                                                                                                    method: "POST"
                                                                                                                          });

                                                                                                                                setRequests(prev =>
                                                                                                                                        prev.filter(r => r.consultationId !== consultationId)
                                                                                                                                              );

                                                                                                                                                  } catch (err) {

                                                                                                                                                        console.error("Decline failed", err);

                                                                                                                                                            }

                                                                                                                                                              };

                                                                                                                                                                return (

                                                                                                                                                                    <div style={{ padding: "20px" }}>

                                                                                                                                                                          <h2>Incoming Telemedicine Consultations</h2>

                                                                                                                                                                                {requests.length === 0 && (
                                                                                                                                                                                        <p>No pending consultation requests.</p>
                                                                                                                                                                                              )}

                                                                                                                                                                                                    {requests.map(req => (

                                                                                                                                                                                                            <div
                                                                                                                                                                                                                      key={req.consultationId}
                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                            border: "1px solid #e5e7eb",
                                                                                                                                                                                                                                                        padding: "20px",
                                                                                                                                                                                                                                                                    marginTop: "15px",
                                                                                                                                                                                                                                                                                borderRadius: "8px",
                                                                                                                                                                                                                                                                                            background: "white"
                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                              >

                                                                                                                                                                                                                                                                                                                        <h3>Facility: {req.facilityName}</h3>

                                                                                                                                                                                                                                                                                                                                  <p><strong>Patient Age:</strong> {req.patientAge}</p>
                                                                                                                                                                                                                                                                                                                                            <p><strong>Symptoms:</strong> {req.symptoms.join(", ")}</p>

                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                                  <strong>Risk Level:</strong>
                                                                                                                                                                                                                                                                                                                                                                              <span style={{ marginLeft: "5px", color: "#ef4444" }}>
                                                                                                                                                                                                                                                                                                                                                                                            {req.riskLevel}
                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ marginTop: "15px" }}>

                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={() => acceptConsultation(req.consultationId)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    background: "#16a34a",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: "10px 16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginRight: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: "6px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cursor: "pointer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Accept Consultation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => declineConsultation(req.consultationId)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                background: "#ef4444",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "10px 16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: "6px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cursor: "pointer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Decline
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default DoctorConsultationRequests;