import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { users } from "../data/users";

const LoginPage = () => {

  const navigate = useNavigate();

    const [username, setUsername] = useState("");
      const [password, setPassword] = useState("");

        const handleLogin = () => {

            const user = users.find(
                  (u) => u.username === username && u.password === password
                      );

                          if (!user) {
                                alert("Invalid username or password");
                                      return;
                                          }

                                              // store role for sidebar and header
                                                  localStorage.setItem("userRole", user.role);
                                                      localStorage.setItem("username", user.username);

                                                          // route based on role
                                                              if (user.role === "doctor") {
                                                                    navigate("/clinical");
                                                                        }

                                                                            if (user.role === "rural-nurse") {
                                                                                  navigate("/rural-nurse");
                                                                                      }

                                                                                          if (user.role === "urban-nurse") {
                                                                                                navigate("/urban-nurse");
                                                                                                    }

                                                                                                        if (user.role === "admin") {
                                                                                                              navigate("/admin");
                                                                                                                  }

                                                                                                                    };

                                                                                                                      return (

                                                                                                                          <div
                                                                                                                                style={{
                                                                                                                                        height: "100vh",
                                                                                                                                                display: "flex",
                                                                                                                                                        justifyContent: "center",
                                                                                                                                                                alignItems: "center",
                                                                                                                                                                        backgroundColor: "#f4f7fb"
                                                                                                                                                                              }}
                                                                                                                                                                                  >

                                                                                                                                                                                        <div
                                                                                                                                                                                                style={{
                                                                                                                                                                                                          width: "380px",
                                                                                                                                                                                                                    background: "white",
                                                                                                                                                                                                                              padding: "40px",
                                                                                                                                                                                                                                        borderRadius: "10px",
                                                                                                                                                                                                                                                  boxShadow: "0 6px 25px rgba(0,0,0,0.1)",
                                                                                                                                                                                                                                                            textAlign: "center"
                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                          >

                                                                                                                                                                                                                                                                                  <h2 style={{ marginBottom: "10px" }}>
                                                                                                                                                                                                                                                                                            GJHealth Login
                                                                                                                                                                                                                                                                                                    </h2>

                                                                                                                                                                                                                                                                                                            <p style={{ marginBottom: "25px", color: "#666" }}>
                                                                                                                                                                                                                                                                                                                      Telemedicine Platform Access
                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                      {/* Username */}
                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                        type="text"
                                                                                                                                                                                                                                                                                                                                                                  placeholder="Username"
                                                                                                                                                                                                                                                                                                                                                                            value={username}
                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setUsername(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                            width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                        padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                    marginBottom: "15px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: "6px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: "1px solid #ccc"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Password */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="Password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginBottom: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: "6px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: "1px solid #ccc"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Login Button */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={handleLogin}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      backgroundColor: "#0b345a",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderRadius: "6px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cursor: "pointer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Login
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default LoginPage;