import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import LoadingSpinner from "../components/LoadingSpinner";
import { login } from "../services/api";

const LoginPage = () => {
  const navigate = useNavigate();
    const [email, setEmail] = useState("");
      const [password, setPassword] = useState("");
        const [loading, setLoading] = useState(false);
          const [error, setError] = useState("");

            const handleLogin = async (e) => {
                e.preventDefault();
                    setLoading(true);
                        setError("");

                            const result = await login(email, password);

                                setLoading(false);

                                    if (!result.success) {
                                          setError(result.message || "Login failed");
                                                return;
                                                    }

                                                        // Save token to local storage
                                                            localStorage.setItem("token", result.token);

                                                                // Redirect to dashboard
                                                                    navigate("/dashboard");
                                                                      };

                                                                        return (
                                                                            <div
                                                                                  style={{
                                                                                          height: "100vh",
                                                                                                  display: "flex",
                                                                                                          justifyContent: "center",
                                                                                                                  alignItems: "center",
                                                                                                                          background: "#e2e8f0",
                                                                                                                                }}
                                                                                                                                    >
                                                                                                                                          <form
                                                                                                                                                  onSubmit={handleLogin}
                                                                                                                                                          style={{
                                                                                                                                                                    width: "350px",
                                                                                                                                                                              background: "white",
                                                                                                                                                                                        padding: "30px",
                                                                                                                                                                                                  borderRadius: "10px",
                                                                                                                                                                                                            boxShadow: "0 2px 6px rgba(0,0,0,0.1)",
                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                  <h2 style={{ textAlign: "center" }}>Login</h2>

                                                                                                                                                                                                                                          {error && (
                                                                                                                                                                                                                                                    <p style={{ color: "red", textAlign: "center", marginBottom: "10px" }}>
                                                                                                                                                                                                                                                                {error}
                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                          <label>Email</label>
                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                            type="email"
                                                                                                                                                                                                                                                                                                                      style={{ width: "100%", padding: "10px", marginBottom: "15px" }}
                                                                                                                                                                                                                                                                                                                                value={email}
                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                          <label>Password</label>
                                                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                                            type="password"
                                                                                                                                                                                                                                                                                                                                                                                      style={{ width: "100%", padding: "10px", marginBottom: "15px" }}
                                                                                                                                                                                                                                                                                                                                                                                                value={password}
                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                    type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                          width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  background: "#1e293b",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: "5px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {loading ? <LoadingSpinner /> : "Login"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default LoginPage;