import React, { useState } from "react";
import { useNavigate } from "react-router-dom";

export default function LoginPage() {
  const navigate = useNavigate();

    const [username, setUsername] = useState("");
      const [password, setPassword] = useState("");
        const [loading, setLoading] = useState(false);
          const [error, setError] = useState("");

            const handleLogin = async (e) => {
                e.preventDefault();
                    setError("");
                        setLoading(true);

                            // Temporary login logic (Option A)
                                if (username === "admin" && password === "admin") {
                                      setLoading(false);
                                            navigate("/dashboard");
                                                  return;
                                                      }

                                                          setError("Invalid username or password");
                                                              setLoading(false);
                                                                };

                                                                  return (
                                                                      <div style={styles.container}>
                                                                            <div style={styles.card}>
                                                                                    <h2 style={styles.title}>Login</h2>

                                                                                            <form onSubmit={handleLogin} style={styles.form}>
                                                                                                      <input
                                                                                                                  type="text"
                                                                                                                              placeholder="Username"
                                                                                                                                          value={username}
                                                                                                                                                      onChange={(e) => setUsername(e.target.value)}
                                                                                                                                                                  style={styles.input}
                                                                                                                                                                            />

                                                                                                                                                                                      <input
                                                                                                                                                                                                  type="password"
                                                                                                                                                                                                              placeholder="Password"
                                                                                                                                                                                                                          value={password}
                                                                                                                                                                                                                                      onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                  style={styles.input}
                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                      {error && <p style={styles.error}>{error}</p>}

                                                                                                                                                                                                                                                                                <button type="submit" style={styles.button} disabled={loading}>
                                                                                                                                                                                                                                                                                            {loading ? "Logging in..." : "Login"}
                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                              </form>
                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                          const styles = {
                                                                                                                                                                                                                                                                                                                            container: {
                                                                                                                                                                                                                                                                                                                                height: "100vh",
                                                                                                                                                                                                                                                                                                                                    display: "flex",
                                                                                                                                                                                                                                                                                                                                        justifyContent: "center",
                                                                                                                                                                                                                                                                                                                                            alignItems: "center",
                                                                                                                                                                                                                                                                                                                                                backgroundColor: "#f4f4f4",
                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                    card: {
                                                                                                                                                                                                                                                                                                                                                        width: "360px",
                                                                                                                                                                                                                                                                                                                                                            padding: "30px",
                                                                                                                                                                                                                                                                                                                                                                backgroundColor: "#fff",
                                                                                                                                                                                                                                                                                                                                                                    borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                        boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                            title: {
                                                                                                                                                                                                                                                                                                                                                                                textAlign: "center",
                                                                                                                                                                                                                                                                                                                                                                                    marginBottom: "20px",
                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                        form: {
                                                                                                                                                                                                                                                                                                                                                                                            display: "flex",
                                                                                                                                                                                                                                                                                                                                                                                                flexDirection: "column",
                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                    input: {
                                                                                                                                                                                                                                                                                                                                                                                                        padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                            marginBottom: "15px",
                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: "6px",
                                                                                                                                                                                                                                                                                                                                                                                                                    border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                        button: {
                                                                                                                                                                                                                                                                                                                                                                                                                            padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                backgroundColor: "#0070f3",
                                                                                                                                                                                                                                                                                                                                                                                                                                    color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                        border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: "6px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                    error: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: "red",
                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginBottom: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                textAlign: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };