import React from "react";
import { BrowserRouter, Routes, Route } from "react-router-dom";

import LoginPage from "./pages/LoginPage";
import DashboardPage from "./pages/DashboardPage";
import Pagesholder from "./pages/Pagesholder";
import ClinicalDashboard from "./pages/ClinicalDashboard";
import MedicineDashboard from "./pages/MedicineDashboard";

import Layout from "./components/Layout";

function App() {
  return (
      <BrowserRouter>
            <Routes>

                    {/* Login */}
                            <Route path="/" element={<LoginPage />} />

                                    {/* Dashboard */}
                                            <Route
                                                      path="/dashboard"
                                                                element={
                                                                            <Layout>
                                                                                          <DashboardPage />
                                                                                                      </Layout>
                                                                                                                }
                                                                                                                        />

                                                                                                                                {/* Clinical */}
                                                                                                                                        <Route
                                                                                                                                                  path="/clinical"
                                                                                                                                                            element={
                                                                                                                                                                        <Layout>
                                                                                                                                                                                      <ClinicalDashboard />
                                                                                                                                                                                                  </Layout>
                                                                                                                                                                                                            }
                                                                                                                                                                                                                    />

                                                                                                                                                                                                                            {/* Medicine */}
                                                                                                                                                                                                                                    <Route
                                                                                                                                                                                                                                              path="/medicine"
                                                                                                                                                                                                                                                        element={
                                                                                                                                                                                                                                                                    <Layout>
                                                                                                                                                                                                                                                                                  <MedicineDashboard />
                                                                                                                                                                                                                                                                                              </Layout>
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                                                                                        {/* Patients */}
                                                                                                                                                                                                                                                                                                                                <Route
                                                                                                                                                                                                                                                                                                                                          path="/patients"
                                                                                                                                                                                                                                                                                                                                                    element={
                                                                                                                                                                                                                                                                                                                                                                <Layout>
                                                                                                                                                                                                                                                                                                                                                                              <Pagesholder title="Patients" />
                                                                                                                                                                                                                                                                                                                                                                                          </Layout>
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Settings */}
                                                                                                                                                                                                                                                                                                                                                                                                                            <Route
                                                                                                                                                                                                                                                                                                                                                                                                                                      path="/settings"
                                                                                                                                                                                                                                                                                                                                                                                                                                                element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Layout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Pagesholder title="Settings" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Layout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Routes>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </BrowserRouter>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default App;